config/routes.rb
Rails.application.routes.draw do
  root 'maps#index'

  resources :maps, only: [:index]
  get "/drops/followees" => 'drops#followees'
  get 'users/me' => 'users#me'
  post "users/search" => 'users#search'
  post "users/filter" => 'users#filter'
  resources :users, only: [:show, :edit, :update] do
    resources :follows, only: [:index]
    resources :drops, only: [:index]
  end

  resources :follows, only: [:create, :destroy]
  resources :drops, only: [:new, :index, :show, :create] do
    resources :comments, only: [:create]
    resources :snaps, only: [:create]
  end

  get "/login", :to => 'sessions#new', :as => 'login'
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  delete 'logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :drops
  has_many :comments
  has_many :snaps
  has_many :follower_follows, foreign_key: "followee_id", class_name: "Follow"
  has_many :followee_follows, foreign_key: "follower_id", class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower
  has_many :followees, through: :followee_follows, source: :followee
  validates :username, :avatar, :uid, presence: true
  validates :uid, uniqueness: true

  def follow(diff_user)
    self.followee_follows.create(followee: diff_user)
  end

  def unfollow(diff_user)
    self.followee_follows.find_by(followee: diff_user).destroy
  end

  def following?(diff_user)
    self.followees.include?(diff_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id]) 
    binding.pry
    if @user.update(username: params[:user][:username])
      redirect_to @user
    else
      flash.now.alert = @user.errors.full_messages.join(', ')
      render plain: {failure: @user.errors.full_messages.join(",")}.to_json, status: 422
    end
  end

  def me
    redirect_to user_path(current_user)
  end

  def search
    query_name = params[:query]
    target = User.find_by(username: query_name)
    if target
      render json: {user_id: target.id}
    else
      status 404
    end
  end

  def filter
    users = []
    if params[:query] && params[:query].length > 0
      users = User.where('UPPER(username) LIKE UPPER(?)', params[:query]+"%")
      .limit(6) 
    end
    render json: {users: users}
  end

end

app/views/users/_follow.html.erb
<%= form_for current_user.followee_follows.build do |f| %>
	<%= hidden_field_tag :followee_id, @user.id %>
	<%= f.submit "+ follow", { :class => "raised orange follow" } %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
<% if current_user.following?(@user) %>
<%= render 'unfollow' %>
<% else %>
<%= render 'follow' %>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.followee_follows.find_by(followee_id: @user.id), html: { method: :delete } do |f| %>
	<%= f.submit "✔ following", { :class => "raised white follow" } %>
<% end %>

app/views/users/_user.html.erb
<%=  link_to user.username, user_path(user) %>

app/views/users/show.html.erb
<div data-view="user" class="user view">
  <header>
    <a href="/" class="home"><i id="map-home" class="material-icons">map</i></a>
    <%= @user.username %>
    <% if current_user == @user %>
      <form id="search-form">
        <input id="search" type="text" autocomplete="off" name="query" placeholder="Find users">
        <button type="submit"><i class="material-icons">search</i></button>
      </form>
      <ul class='hide suggestions' data-role='suggestions'></ul>
    <% end %>
    <a href="/logout" class="logout" data-method="delete"><i id="user-logout" class="material-icons">power_settings_new</i></a>
  </header>

  <div class="profile">
    <div class="avatar">
      <img id="avatar" src="<%= @user.avatar %>">
    </div>
    <div class="follow-form">
      <% if current_user != @user %>
        <%= render 'follow_form' %>
      <% end %>
    </div>
  </div>
  <div class="profile-info">
    <div data-role="show-followers">
      <%= pluralize(@user.followers.count, 'follower') %>
    </div>
    <div data-role="show-followees">
      <%= @user.followees.count %> following
    </div>
    <div data-role="show-drop-map" id="drops">
      <%= link_to pluralize(@user.drops.count, 'drop'), user_drops_path(@user) %>
    </div>
  </div>


  <div class="pure-g content drop-thumbs">
    <% if current_user == @user %>
      <% @user.drops.each do |drop| %>
        <% if drop.photo_file_name.nil? %>
          <div class="pure-u-1-4 pure-u-lg-1-8 open-drop text-only"><%= link_to drop.text, drop_path(drop) %></div>
        <% else %>
          <div class="pure-u-1-4 pure-u-lg-1-8 open-drop"><%=  link_to image_tag(drop.photo(:thumb), { :class => "pure-img" }), drop_path(drop) %>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div data-view="user-form" class="user-container hide">
  <%= render partial: "user_form" %>
</div>


<%= render partial: "handlebars_show_follower" %>
<%= render partial: "handlebars_show_drop" %>
<%= render partial: "handlebars_suggestion" %>